steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - hello_worlddd
  - --source=.
  - --trigger-http
  - --runtime=python37
  - --allow-unauthenticated
  env:
- 'CLOUDSDK_COMPUTE_REGION=southamerica-east1'
- 'CLOUDSDK_COMPUTE_ZONE=southamerica-east1'
  
